---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    app: webserver
    author: intelliqit
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        app: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:    
              cpu: 200m
              memory: 150M

 


