---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        requests:
          cpu: 100m
          memory: 64M
        limits:
          cpu: 200m
          memory: 128M
...
